/**
 * Watermark - Bottom-right credit badge.
 */

import { useCurrentFrame, interpolate } from "remotion";
import { colors, fonts } from "./theme";

interface WatermarkProps {
  text?: string;
  delay?: number;
}

export function Watermark({
  text = "Generated by Claude Code + Remotion",
  delay = 15,
}: WatermarkProps) {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame - delay, [0, 15], [0, 0.4], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return (
    <div
      style={{
        position: "absolute",
        bottom: 30,
        right: 40,
        opacity,
        fontSize: 11,
        color: colors.muted,
        fontFamily: fonts.mono,
        letterSpacing: "0.08em",
        textTransform: "uppercase" as const,
      }}
    >
      {text}
    </div>
  );
}
